### PR TITLE
Transform pages to ejs render-ready templates

### PR DESCRIPTION
**Pull request by ADjenkov**
I'm proposing these **placeholder** names:
- CamelCaseName
- PascalCaseName
- OriginalName - unchanged name of the file that the user passed through Fusion. We need such a placeholder because of the file names in the imports/includes, since they have to be exact as the user set them. 

For the **CamelCaseName/PascalCaseName** I'm planning to use [_lodash.camelCase](https://lodash.com/docs/4.17.4#camelCase). More info about this -> in the upcomming starter-kits extension

### CODE REVIEW

**Comment by manoldonev** [comment]
Maybe we should keep a .gitignore file at the root level as git goes completely mad with this PR?

**Comment by manoldonev** [comment]
So how do we test this now? :)

**Comment by manoldonev** [comment]
Should the variable names be capitalized or camelCaseName, pascalCaseName, originalName ?

**Review by lini — APPROVED** [review]

**Comment by ADjenkov** [comment]
@lini @manoldonev @MIYankov @borisKarastanev @vegeorgi @DimitarTodorov at this point you can test it with https://github.com/NativeScript/nativescript-page-templates/tree/test

**Review by lini — APPROVED** [review]

**Pull request merged**
